name: "retail_dwh"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_dwh:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
    reporting:
      +materialized: table
